### ISSUE TITLE
The URL Link is dead

### ISSUE THREAD

**Issue by etchelepi** [ptanov/docker-yi-360-studio#1]
THe URL is dead in the Readme. Should it be updated?

**Comment by ptanov** [comment]
Hello @etchelepi , unfortunately something happened with the support for YI 360 camera :(
As you can see all links are broken: https://help.yitechnology.com/hc/en-us/articles/115003456113-Where-can-I-download-stitching-software-for-PC- points to same page, https://help.yitechnology.com/hc/en-us/articles/115000467093-Where-can-I-download-YI-360-App- to http://www.xiaoyi.com/download/yi360 which points to missing andoid app...

Luckily you can get it from already build docker image - first you need to start docker container (follow instructions from https://github.com/ptanov/docker-yi-360-studio#use ) and then you can copy install package using: `docker cp yi-360-studio:/dist/YI360Installer1.0.3.0.exe .`

**Comment by Nopius** [comment]
This is new working URL: https://api.yitechnology.com/yi-360-vr-camera-desktopsoftware 

other links (firmware, manuals) you can find here: https://api.yitechnology.com/yi-360-vr-camera
